<?xml version="1.0" encoding="UTF-8"?><testrun name="CategoryDAOTestCase" project="ShoppingCartBackEnd" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="com.niit.shoppingcart.CategoryDAOTestCase" time="0.16">
    <testcase name="saveTestCase" classname="com.niit.shoppingcart.CategoryDAOTestCase" time="0.16">
      <error>org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [insert into Category (description, name, id) values (?, ?, ?)]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement&#13;
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:146)&#13;
	at org.springframework.orm.hibernate4.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:730)&#13;
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:592)&#13;
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)&#13;
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:504)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:292)&#13;
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)&#13;
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)&#13;
	at com.sun.proxy.$Proxy26.save(Unknown Source)&#13;
	at com.niit.shoppingcart.CategoryDAOTestCase.saveTestCase(CategoryDAOTestCase.java:44)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement&#13;
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123)&#13;
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)&#13;
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:196)&#13;
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:96)&#13;
	at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.buildBatchStatement(AbstractBatchImpl.java:152)&#13;
	at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.getBatchStatement(AbstractBatchImpl.java:141)&#13;
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3102)&#13;
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3581)&#13;
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:103)&#13;
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:461)&#13;
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:347)&#13;
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)&#13;
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)&#13;
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)&#13;
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)&#13;
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)&#13;
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)&#13;
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:584)&#13;
	... 33 more&#13;
Caused by: org.h2.jdbc.JdbcSQLException: Column "ID" not found; SQL statement:
insert into Category (description, name, id) values (?, ?, ?) [42122-191]&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)&#13;
	at org.h2.message.DbException.get(DbException.java:179)&#13;
	at org.h2.message.DbException.get(DbException.java:155)&#13;
	at org.h2.table.Table.getColumn(Table.java:680)&#13;
	at org.h2.command.Parser.parseColumn(Parser.java:866)&#13;
	at org.h2.command.Parser.parseColumnList(Parser.java:850)&#13;
	at org.h2.command.Parser.parseInsert(Parser.java:1050)&#13;
	at org.h2.command.Parser.parsePrepared(Parser.java:411)&#13;
	at org.h2.command.Parser.parse(Parser.java:315)&#13;
	at org.h2.command.Parser.parse(Parser.java:287)&#13;
	at org.h2.command.Parser.prepareCommand(Parser.java:252)&#13;
	at org.h2.engine.Session.prepareLocal(Session.java:560)&#13;
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:264)&#13;
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:159)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
	at org.h2.engine.SessionRemote.done(SessionRemote.java:624)&#13;
	at org.h2.command.CommandRemote.prepare(CommandRemote.java:68)&#13;
	at org.h2.command.CommandRemote.&lt;init&gt;(CommandRemote.java:45)&#13;
	at org.h2.engine.SessionRemote.prepareCommand(SessionRemote.java:494)&#13;
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)&#13;
	at org.h2.jdbc.JdbcPreparedStatement.&lt;init&gt;(JdbcPreparedStatement.java:73)&#13;
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)&#13;
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:103)&#13;
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)&#13;
	... 48 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
